kind: Deployment
apiVersion: apps/v1
metadata:
  name: book-store
  namespace: '{{ meta.namespace }}'
spec:
  replicas: "{{size}}"
  selector:
    matchLabels:
      app: book-store
  template:
    metadata:
      labels:
        app: book-store
    spec:
      containers:
      - name: book-store
        image: "akash125/pyapp:latest"
        ports:
        - containerPort: 3000
